"""add interpretations table

Revision ID: 6ef74b9888f4
Revises: 9eb985eac4fa
Create Date: 2026-05-29 21:57:08.271472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef74b9888f4'
down_revision: Union[str, Sequence[str], None] = '9eb985eac4fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interpretations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('change_id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('interpreted_at', sa.DateTime(), nullable=False),
    sa.Column('visa_category', sa.String(), nullable=True),
    sa.Column('change_type_label', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('evidence_implications', sa.Text(), nullable=True),
    sa.Column('review_priority', sa.String(), nullable=True),
    sa.Column('raw_llm_response', sa.Text(), nullable=True),
    sa.Column('governance_flagged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['regulatory_changes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interpretations')
    # ### end Alembic commands ###
