"""add regulatory_changes table

Revision ID: d1b412ebafcf
Revises: fa97883e2a5b
Create Date: 2026-05-29 21:08:00.993418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b412ebafcf'
down_revision: Union[str, Sequence[str], None] = 'fa97883e2a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulatory_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('current_hash', sa.String(length=64), nullable=False),
    sa.Column('delta_summary', sa.Text(), nullable=True),
    sa.Column('added_sentences', sa.Text(), nullable=True),
    sa.Column('removed_sentences', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('filtered_out', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['regulatory_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regulatory_changes')
    # ### end Alembic commands ###
